import Link from "next/link";
const EXE="https://github.com/geleia328/wimmsg/releases/latest/download/BakersWhisper.exe";
const files=[["wim_bridge_gui.py","Bridge Python completo"],["requirements.txt","Dependências Python"],["WIMBridge.zip","Addon pronto para extrair"]];
export default function Download(){return <main className="min-h-dvh bg-slate-950 px-4 py-10 text-slate-100 sm:px-6"><div className="mx-auto max-w-4xl">
 <header className="text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-gradient-to-br from-amber-300 to-orange-600 text-4xl shadow-2xl shadow-amber-900/30">🥐</div><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-5xl">Bakers Whisper</h1><p className="mt-3 text-slate-400">Receba e responda whispers do WoW pelo navegador</p></header>
 <section className="mt-8 rounded-2xl border border-emerald-500/30 bg-slate-900 p-6 text-center"><div className="text-4xl">⬇️</div><h2 className="mt-2 text-2xl font-bold">Baixar para Windows</h2><p className="mt-2 text-sm text-slate-400">Aplicativo pronto pra usar — só baixar e abrir.<br/>Sem instalar Python. API URL e Token podem ser alterados dentro do app.</p><a href={EXE} className="mt-6 inline-flex rounded-xl bg-emerald-400 px-7 py-4 text-lg font-black text-slate-950 shadow-lg shadow-emerald-900/30">📥 Baixar BakersWhisper.exe</a><p className="mt-3 text-xs text-slate-500">Windows 10 ou 11 · aproximadamente 30 MB</p></section>
 <div className="mt-5 rounded-xl border border-amber-500/40 bg-amber-500/10 p-5 text-sm text-amber-100"><b>⚠ Aviso do Windows Defender</b><p className="mt-2 text-amber-100/80">Como o app não é assinado, o Windows pode mostrar “Windows protegeu o seu PC”. É normal: clique em <b>Mais informações</b> e depois em <b>Executar assim mesmo</b>.</p></div>
 <section className="card mt-6"><h2 className="text-xl font-bold">Como usar</h2><ol className="mt-4 space-y-3">{["Abra o WoW em cada janela que você quer monitorar.","Em cada janela, digite /chatlog e aperte Enter. Faça isso toda vez que abrir o jogo.","Abra o BakersWhisper.exe. Ele listará as janelas detectadas.","Confira a seção Servidor. Se necessário, informe este site e o BRIDGE_TOKEN.","Digite o nome completo no formato Nome-Reino ao lado de cada janela.","Clique em ▶ Iniciar. As janelas serão renomeadas para wow1, wow2, etc.","Abra o painel no navegador — pode ser no celular também!"] .map((text,i)=><li key={text} className="flex gap-3 rounded-xl bg-slate-950 p-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-amber-400 text-xs font-black text-slate-950">{i===6?"✓":i+1}</span><p className="text-sm text-slate-300">{text}</p></li>)}</ol></section>
 <section className="mt-6 rounded-2xl border border-fuchsia-500/30 bg-fuchsia-950/20 p-5"><h2 className="font-bold text-fuchsia-300">⚙ Controle GSE — opcional</h2><p className="mt-2 text-sm text-slate-400">Instale o GSE - Advanced Macros, coloque sua macro em uma tecla e configure a mesma tecla em <Link className="text-fuchsia-300 underline" href="/gse">⚙ GSE</Link>. A rotação roda em background e pausa automaticamente durante respostas.</p></section>
 <section className="card mt-6"><h2 className="font-bold">❓ Problemas comuns</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{[["Windows bloqueou o programa","Use Mais informações → Executar assim mesmo."],["Janelas não detectadas","Abra o WoW antes do app e clique em Rescan."],["Log mostra /chatlog ausente","Digite /chatlog dentro daquela janela."],["Whisper não é enviado","Confira se o personagem está online em Contas."],["Antivírus deletou o EXE","Adicione a pasta como exceção e baixe novamente."],["Addon não carrega","Evite pasta WIMBridge/WIMBridge duplicada e habilite addons desatualizados."]].map(([a,b])=><div key={a} className="rounded-lg bg-slate-950 p-3"><b className="text-sm">{a}</b><p className="mt-1 text-xs text-slate-500">{b}</p></div>)}</div></section>
 <section className="card mt-6"><h2 className="font-bold">📦 Arquivos mais recentes</h2><p className="mt-2 text-sm text-slate-400">Bridge e addon com foco robusto, dedupe, controles de relay e delays configuráveis.</p><div className="mt-4 flex flex-wrap gap-2">{files.map(([file,label])=><a key={file} href={`/api/download/${file}`} className="rounded-lg border border-slate-700 px-4 py-2 text-sm hover:border-amber-400"><b>{label}</b><span className="block text-[10px] text-slate-500">{file}</span></a>)}</div><div className="mt-4 rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-xs text-amber-100">O addon deve ficar em <code>_retail_\Interface\AddOns\WIMBridge\WIMBridge.toc</code>. Teste no jogo com <code>/wimbridge who</code>.</div></section>
 <footer className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/" className="rounded-lg bg-amber-400 px-5 py-3 font-bold text-slate-950">Abrir painel</Link><Link href="/setup" className="rounded-lg border border-slate-700 px-5 py-3">Setup técnico</Link></footer>
 </div></main>}
