"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { CharacterSummary, ChatMessage, Conversation, WindowStatus } from "@/lib/types";
import { useNotifications } from "./useNotifications";

const POLL=2000; const j=async<T,>(url:string,init?:RequestInit):Promise<T>=>{const r=await fetch(url,init);if(!r.ok)throw new Error(await r.text());return r.json()};
const ago=(value:string)=>{const seconds=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return "agora";if(seconds<3600)return `${Math.floor(seconds/60)}m`;if(seconds<86400)return `${Math.floor(seconds/3600)}h`;return `${Math.floor(seconds/86400)}d`};
const palette=["bg-sky-500/15 text-sky-300","bg-violet-500/15 text-violet-300","bg-emerald-500/15 text-emerald-300","bg-rose-500/15 text-rose-300","bg-amber-500/15 text-amber-300"];
const color=(name:string)=>palette[[...name].reduce((n,c)=>n+c.charCodeAt(0),0)%palette.length];
export default function ChatApp(){
 const [conversations,setConversations]=useState<Conversation[]>([]),[characters,setCharacters]=useState<CharacterSummary[]>([]),[windows,setWindows]=useState<WindowStatus[]>([]),[filter,setFilter]=useState("ALL"),[selected,setSelected]=useState<{character:string;player:string}|null>(null),[messages,setMessages]=useState<ChatMessage[]>([]),[draft,setDraft]=useState(""),[sending,setSending]=useState(false),[newCharacter,setNewCharacter]=useState(""),[newPlayer,setNewPlayer]=useState(""),[drawer,setDrawer]=useState(true),[notifOpen,setNotifOpen]=useState(false),[bridgeUp,setBridgeUp]=useState(true); const bottom=useRef<HTMLDivElement>(null),lastIncoming=useRef(-1);const notif=useNotifications();
 const refresh=useCallback(async()=>{try{const [c,ch,s]=await Promise.all([j<{conversations:Conversation[]}>("/api/conversations"),j<{characters:CharacterSummary[]}>("/api/characters"),j<{windows:WindowStatus[]}>("/api/status")]);setConversations(c.conversations);setCharacters(ch.characters);setWindows(s.windows);setBridgeUp(true)}catch{setBridgeUp(false)}},[]);
 const fetchMessages=useCallback(async()=>{if(!selected)return;try{setMessages((await j<{messages:ChatMessage[]}>(`/api/conversations/${encodeURIComponent(selected.character)}/${encodeURIComponent(selected.player)}`)).messages)}catch{}},[selected]);
 useEffect(()=>{void refresh();const id=setInterval(refresh,POLL);return()=>clearInterval(id)},[refresh]); useEffect(()=>{void fetchMessages();const id=setInterval(fetchMessages,POLL);return()=>clearInterval(id)},[fetchMessages]); useEffect(()=>bottom.current?.scrollIntoView({behavior:"smooth"}),[messages]);
 useEffect(()=>{const poll=async()=>{try{const data=await j<{messages:ChatMessage[];latestId:number}>(`/api/incoming/recent?since=${Math.max(0,lastIncoming.current)}`);if(lastIncoming.current>=0)data.messages.filter(m=>m.id>lastIncoming.current).forEach(notif.notifyIncoming);lastIncoming.current=Math.max(lastIncoming.current,data.latestId)}catch{}};void poll();const id=setInterval(poll,POLL);return()=>clearInterval(id)},[notif.notifyIncoming]);
 const status=new Map(windows.filter(w=>w.character).map(w=>[w.character,w])); const online=windows.filter(w=>w.online).length; const filtered=filter==="ALL"?conversations:conversations.filter(c=>c.character===filter); const mismatch=useMemo(()=>{if(!selected)return false;const a=selected.character.split("-").at(-1),b=selected.player.split("-").at(-1);return selected.character.includes("-")&&selected.player.includes("-")&&a?.toLowerCase()!==b?.toLowerCase()},[selected]);
 const choose=(character:string,player:string)=>{setSelected({character,player});setDrawer(false)}; const create=(e:FormEvent)=>{e.preventDefault();if(newCharacter.trim()&&newPlayer.trim())choose(newCharacter.trim(),newPlayer.trim())};
 const send=async()=>{if(!selected||!draft.trim()||sending)return;setSending(true);try{await j(`/api/conversations/${encodeURIComponent(selected.character)}/${encodeURIComponent(selected.player)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body:draft.trim()})});setDraft("");await fetchMessages();await refresh()}finally{setSending(false)}};
 return <main className="flex h-dvh min-h-[600px] flex-col overflow-hidden bg-slate-950 text-slate-100">
  <header className="relative z-30 flex h-16 shrink-0 items-center gap-3 border-b border-slate-800 bg-slate-950/95 px-3 backdrop-blur sm:px-5"><button className="grid h-10 w-10 place-items-center rounded-xl border border-slate-700 text-xl lg:hidden" onClick={()=>setDrawer(v=>!v)}>☰</button><div className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-amber-300 to-orange-600 text-xl shadow-lg shadow-amber-900/20">🥐</div><div className="min-w-0"><h1 className="truncate font-black tracking-tight">Bakers Whisper</h1><p className="truncate text-[11px] text-slate-400"><span className={`mr-1 inline-block h-2 w-2 rounded-full ${bridgeUp?"bg-emerald-400":"bg-rose-500"}`}/>{online} janelas online · {conversations.length} conversas</p></div><nav className="ml-auto flex items-center gap-1.5 text-xs sm:gap-2"><button className="rounded-lg border border-slate-700 px-2.5 py-2" onClick={()=>setNotifOpen(v=>!v)}>{notif.prefs.sound?"🔔":"🔕"}</button><Link className="hidden rounded-lg bg-amber-400 px-3 py-2 font-bold text-slate-950 sm:block" href="/download">Download</Link><Link className="rounded-lg border border-emerald-700 px-2.5 py-2 text-emerald-300" href="/accounts">Contas</Link><Link className="rounded-lg border border-fuchsia-700 px-2.5 py-2 text-fuchsia-300" href="/gse">GSE</Link><Link className="hidden rounded-lg border border-slate-700 px-3 py-2 sm:block" href="/setup">Setup</Link></nav>
  {notifOpen&&<div className="absolute right-3 top-14 w-72 rounded-xl border border-slate-700 bg-slate-900 p-4 shadow-2xl"><b>Notificações</b><label className="mt-3 flex justify-between text-sm">Som <input type="checkbox" checked={notif.prefs.sound} onChange={e=>notif.setPrefs({...notif.prefs,sound:e.target.checked})}/></label><label className="mt-3 flex justify-between text-sm">Desktop <input type="checkbox" checked={notif.prefs.desktop} onChange={async e=>{if(e.target.checked)await notif.requestDesktop();notif.setPrefs({...notif.prefs,desktop:e.target.checked})}}/></label><label className="mt-3 block text-sm">Volume <input className="w-full accent-amber-400" type="range" min="0" max="1" step=".1" value={notif.prefs.volume} onChange={e=>notif.setPrefs({...notif.prefs,volume:Number(e.target.value)})}/></label><button onClick={notif.playChime} className="mt-3 text-xs text-amber-300">▶ Testar som</button></div>}</header>
  <div className="flex shrink-0 gap-2 overflow-x-auto border-b border-slate-800 px-3 py-2 scrollbar-none"><button onClick={()=>setFilter("ALL")} className={`pill ${filter==="ALL"?"pill-active":""}`}>Todos</button>{characters.map(c=><button key={c.character} onClick={()=>setFilter(c.character)} className={`pill ${filter===c.character?"pill-active":""}`}><i className={`h-2 w-2 rounded-full ${status.get(c.character)?.online?"bg-emerald-400":"bg-slate-600"}`}/>{c.character}{c.pendingOut>0&&<b className="rounded bg-amber-400 px-1 text-[10px] text-slate-950">{c.pendingOut}</b>}</button>)}</div>
  <div className="relative flex min-h-0 flex-1"><div onClick={()=>setDrawer(false)} className={`absolute inset-0 z-10 bg-black/60 transition lg:hidden ${drawer?"opacity-100":"pointer-events-none opacity-0"}`}/><aside className={`absolute inset-y-0 left-0 z-20 flex w-[min(92vw,24rem)] flex-col border-r border-slate-800 bg-slate-950 transition-transform lg:static lg:translate-x-0 ${drawer?"translate-x-0":"-translate-x-full"}`}><form onSubmit={create} className="border-b border-slate-800 p-3"><p className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">Nova conversa</p><div className="flex gap-2"><input list="chars" value={newCharacter} onChange={e=>setNewCharacter(e.target.value)} className="field min-w-0 flex-1" placeholder="Seu personagem"/><datalist id="chars">{characters.map(c=><option key={c.character} value={c.character}/>)}</datalist><input value={newPlayer} onChange={e=>setNewPlayer(e.target.value)} className="field min-w-0 flex-1" placeholder="Whisper para"/><button className="rounded-lg bg-amber-400 px-3 font-black text-slate-950">+</button></div></form><div className="min-h-0 flex-1 overflow-y-auto p-2">{filtered.map(c=><button key={`${c.character}/${c.player}`} onClick={()=>choose(c.character,c.player)} className={`mb-1 w-full rounded-xl p-3 text-left transition hover:bg-slate-900 ${selected?.character===c.character&&selected.player===c.player?"bg-slate-900 ring-1 ring-amber-500/40":""}`}><div className="flex items-center gap-2"><b className="min-w-0 flex-1 truncate">{c.player}</b><time className="text-[10px] text-slate-500">{ago(c.lastAt)}</time></div><span className={`mt-1 inline-block max-w-full truncate rounded px-1.5 py-0.5 text-[10px] ${color(c.character)}`}>{c.character}</span><p className="mt-1 truncate text-xs text-slate-500">{c.lastDirection==="outgoing"?"Você: ":""}{c.lastBody}</p></button>)}{!filtered.length&&<p className="p-8 text-center text-sm text-slate-500">Nenhuma conversa ainda.</p>}</div></aside>
  <section className="flex min-w-0 flex-1 flex-col bg-[radial-gradient(circle_at_top_right,rgba(245,158,11,.06),transparent_35%)]">{!selected?<div className="grid flex-1 place-items-center p-8 text-center"><div><div className="text-5xl">💬</div><h2 className="mt-4 text-xl font-bold">Selecione uma conversa</h2><p className="mt-2 text-sm text-slate-500">Seus whispers aparecerão aqui em tempo real.</p><button onClick={()=>setDrawer(true)} className="mt-5 rounded-lg bg-amber-400 px-4 py-2 text-sm font-bold text-slate-950 lg:hidden">Abrir conversas</button></div></div>:<><div className="flex h-16 shrink-0 items-center gap-3 border-b border-slate-800 px-3 sm:px-5"><button onClick={()=>setDrawer(true)} className="text-xl lg:hidden">‹</button><div className="min-w-0"><p className="truncate">Whisper com <b className="text-amber-300">{selected.player}</b></p><p className="truncate text-xs text-slate-500">via <span className={color(selected.character)}>{selected.character}</span> · {status.get(selected.character)?.online?"online":"offline"}</p></div></div>{mismatch&&<div className="m-3 rounded-lg border border-rose-800 bg-rose-950/40 px-4 py-2 text-xs text-rose-200">⚠ Personagem e jogador parecem estar em reinos diferentes.</div>}<div className="min-h-0 flex-1 overflow-y-auto px-3 py-4 sm:px-6">{messages.map(m=><div key={m.id} className={`mb-2 flex ${m.direction==="outgoing"?"justify-end":"justify-start"}`}><div className={`max-w-[88%] rounded-2xl px-3.5 py-2.5 text-sm shadow sm:max-w-[70%] ${m.direction==="outgoing"?"rounded-br-sm bg-amber-500 text-slate-950":"rounded-bl-sm border border-slate-700 bg-slate-800"}`}><p className="whitespace-pre-wrap break-words">{m.body}</p><div className={`mt-1 flex justify-end gap-2 text-[9px] ${m.direction==="outgoing"?"text-amber-950/70":"text-slate-500"}`}><time>{new Date(m.createdAt).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</time>{m.direction==="outgoing"&&<span>{m.status==="pending"?"◷ pendente":m.status==="failed"?"⚠ falhou":"✓ enviado"}</span>}</div></div></div>)}<div ref={bottom}/></div><div className="shrink-0 border-t border-slate-800 bg-slate-950 p-2 pb-[max(.5rem,env(safe-area-inset-bottom))] sm:p-4"><div className="mx-auto flex max-w-5xl items-end gap-2"><textarea maxLength={255} rows={1} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}} className="field max-h-32 min-h-11 flex-1 resize-none" placeholder={`Responder ${selected.player} pela janela ${selected.character}...`}/><button onClick={()=>void send()} disabled={!draft.trim()||sending} className="h-11 rounded-xl bg-amber-400 px-4 font-bold text-slate-950 disabled:opacity-40 sm:px-6">Enviar</button></div><p className="mt-1 hidden text-center text-[10px] text-slate-600 sm:block">O bridge focará {selected.character} e digitará /w {selected.player} …</p></div></>}</section></div></main>
}
