"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { DEFAULT_CONTROLS, type Controls } from "@/lib/control-client";
import type { GseRow, WindowStatus } from "@/lib/types";

type DelayKey = "whisperChatOpenDelayMs"|"whisperFocusDelayMs"|"whisperKeystrokeDelayMs"|"whisperChatSendDelayMs"|"whisperChatCloseDelayMs"|"whisperAfterSendDelayMs"|"queuePollMs";
const delayInfo: Array<[DelayKey,string,string?]> = [
 ["whisperChatOpenDelayMs","⏱ Abrir chat no jogo","(abrir /w)"], ["whisperFocusDelayMs","⏱ Delay de foco antes de digitar"],
 ["whisperKeystrokeDelayMs","⏱ Entre cada tecla digitada","(typing)"], ["whisperChatSendDelayMs","⏱ Enviar mensagem (Enter)"],
 ["whisperChatCloseDelayMs","⏱ Fechar chat (Escape)","(após enviar)"], ["whisperAfterSendDelayMs","⏱ Depois de enviar whisper"], ["queuePollMs","⏱ Poll da fila de whisper"]
];
const relayCards:Array<[keyof Controls,string,string,string,string]> = [
 ["wimScreenOcrEnabled","🖥 Leitor da janela WIM (sem addon, sem log)","Tira um print da janela do WoW a cada 2s e lê a conversa do WIM direto da tela com OCR. Só mensagens RECEBIDAS entram (a janela define seu personagem, o nome falado define o comprador) — roteamento sempre seguro. Útil quando o WoWChatLog/WoWCombatLog não são criados.","WIM OCR","emerald"],
 ["ocrRelayEnabled","📷 OCR da tela (sem log, sem microfone)","O addon desenha cada whisper numa faixa preta/amarela no topo da janela do WoW; o bridge tira um print em segundo plano só dessa faixa e lê com o OCR nativo do Windows. Os nomes saem exatos porque vêm do quadro, não de reconhecimento de fala. A faixa some sozinha após 6s. Esconda com /wimbridge screen.","OCR","fuchsia"],
 ["combatRelayEnabled","🗡 Relay pelo combatlog (tempo real)","O addon espelha cada whisper como um emote no WoWCombatLog.txt, que grava no disco quase instantaneamente. Requer /combatlog ativo. O emote pode ficar visível para jogadores próximos; desative aqui ou com /wimbridge combat se incomodar.","COMBAT","amber"],
 ["voiceRelayEnabled","🎙 Modo voz (tempo real)","O addon fala cada whisper no jogo com os nomes soletrados em alfabeto fonético; o bridge ouve pelo microfone e manda direto para o site. Requer SpeechRecognition e um microfone ligado.","VOZ","sky"]
];
const borderTone=(name:string)=>name==="emerald"?"border-emerald-500/30":name==="fuchsia"?"border-fuchsia-500/30":name==="amber"?"border-amber-500/30":"border-sky-500/30";
export default function GseView(){
 const [windows,setWindows]=useState<WindowStatus[]>([]),[states,setStates]=useState<Record<string,GseRow>>({}),[controls,setControls]=useState<Controls>(DEFAULT_CONTROLS),[draft,setDraft]=useState<Record<DelayKey,string>>({whisperChatOpenDelayMs:"1000",whisperFocusDelayMs:"2000",whisperKeystrokeDelayMs:"100",whisperChatSendDelayMs:"1000",whisperChatCloseDelayMs:"500",whisperAfterSendDelayMs:"1000",queuePollMs:"1500"}),[dirty,setDirty]=useState(false),[busy,setBusy]=useState("");
 const load=useCallback(async()=>{try{const [w,g,c]=await Promise.all([fetch("/api/status").then(r=>r.json()),fetch("/api/gse").then(r=>r.json()),fetch("/api/control").then(r=>r.json())]);setWindows(w.windows);setStates(Object.fromEntries(g.states.map((x:GseRow)=>[x.character,x])));setControls(c.controls);if(!dirty)setDraft(Object.fromEntries(delayInfo.map(([k])=>[k,String(c.controls[k])])) as Record<DelayKey,string>)}catch{}},[dirty]);
 useEffect(()=>{void load();const id=setInterval(load,2000);return()=>clearInterval(id)},[load]);
 const chars=useMemo(()=>[...new Set([...windows.map(w=>w.character),...Object.keys(states)].filter(Boolean))].sort(),[windows,states]);
 const adminHeaders=()=>({"content-type":"application/json","x-admin-token":localStorage.getItem("bakers-whisper:admin-token")||""});
 const updateControls=async(patch:Partial<Controls>)=>{const r=await fetch("/api/control",{method:"POST",headers:adminHeaders(),body:JSON.stringify(patch)});if(!r.ok){alert("Token admin inválido. Entre em Config e salve o token admin.");return false}setControls((await r.json()).controls);return true};
 const updateOne=async(character:string,patch:Partial<{running:boolean;keybind:string;intervalMs:number}>)=>{const old=states[character]??{character,running:false,keybind:"1",intervalMs:2000,updatedAt:""};setBusy(character);try{await fetch(`/api/gse/${encodeURIComponent(character)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({running:old.running,keybind:old.keybind,intervalMs:old.intervalMs,...patch})});await load()}finally{setBusy("")}};
 const bulk=async(action:"startAll"|"stopAll")=>{setBusy(action);try{await fetch("/api/gse",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,characters:chars})});await load()}finally{setBusy("")}};
 const tone=(name:string,on:boolean)=>on?name==="emerald"?"bg-emerald-500 text-slate-950":name==="fuchsia"?"bg-fuchsia-500 text-white":name==="amber"?"bg-amber-500 text-slate-950":"bg-sky-500 text-slate-950":"bg-slate-700 text-slate-300";
 return <main className="min-h-dvh bg-slate-950 px-4 py-6 text-slate-100 sm:px-6 sm:py-8"><div className="mx-auto max-w-7xl">
  <header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-5"><div><Link href="/" className="text-xs text-slate-400 hover:text-amber-300">← voltar ao chat</Link><h1 className="mt-2 text-2xl font-bold sm:text-3xl">⚙ Controle GSE</h1><p className="mt-1 text-sm text-slate-400">Rotação de macros por personagem, sem tirar o foco da janela atual.</p></div><span className="rounded-full bg-fuchsia-500/15 px-3 py-1 text-xs text-fuchsia-300">{Object.values(states).filter(s=>s.running).length} rodando</span></header>
  <section className="mt-6 rounded-xl border border-slate-800 bg-slate-900 p-4 sm:p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Controle global</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{[["bridgeReaderEnabled","Leitor de janelas/whispers","Mantém scan de contas + leitura do chat log ativa.","emerald"],["gseMasterEnabled","Master GSE","Se desligado, nenhuma janela recebe clique/tecla GSE.","fuchsia"]].map(([key,label,desc,t])=><div key={key} className="flex items-center justify-between gap-3 rounded-lg bg-slate-950 p-4"><div><b>{label}</b><p className="text-xs text-slate-500">{desc}</p></div><button onClick={()=>void updateControls({[key]:!controls[key as keyof Controls]})} className={`shrink-0 rounded px-4 py-2 text-xs font-bold ${tone(t,Boolean(controls[key as keyof Controls]))}`}>{controls[key as keyof Controls]?"ON":"OFF"}</button></div>)}</div>
  {relayCards.map(([key,title,desc,label,t])=><div key={key} className={`mt-4 rounded-lg border bg-slate-950 p-4 ${borderTone(t)}`}><div className="flex items-center justify-between gap-3"><div><div className="font-bold">{title}</div><p className="mt-1 text-xs leading-relaxed text-slate-500">{desc}</p></div><button onClick={()=>void updateControls({[key]:!controls[key]})} className={`shrink-0 rounded px-4 py-2 text-xs font-bold ${tone(t,Boolean(controls[key]))}`}>{label} {controls[key]?"ON":"OFF"}</button></div></div>)}
  <div className="mt-4 flex items-center justify-between gap-3 rounded-lg border border-slate-700 bg-slate-950 p-4"><div><b>Fechar chat do jogo após enviar (Escape)</b><p className="text-xs text-slate-500">Fecha o campo de chat para não atrapalhar o GSE. A próxima mensagem reabre o chat sozinha.</p></div><button onClick={()=>void updateControls({whisperCloseChatEnabled:!controls.whisperCloseChatEnabled})} className={`shrink-0 rounded px-4 py-2 text-xs font-bold ${tone("emerald",controls.whisperCloseChatEnabled)}`}>{controls.whisperCloseChatEnabled?"ON":"OFF"}</button></div>
  <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{delayInfo.map(([key,label,hint])=><label key={key} className="text-xs text-slate-400">{label} {hint&&<span className="text-slate-600">{hint}</span>}<input type="number" min="0" max={key==="queuePollMs"?30000:3000} step="50" value={draft[key]} onChange={e=>{setDirty(true);setDraft({...draft,[key]:e.target.value})}} className="mt-1 w-full rounded bg-slate-800 px-2 py-1.5 text-sm text-slate-100"/></label>)}</div><div className="mt-4 flex flex-col items-start gap-2 sm:flex-row sm:items-center"><button disabled={!dirty} onClick={async()=>{const patch=Object.fromEntries(delayInfo.map(([k])=>[k,Number(draft[k])])) as Partial<Controls>;if(Object.values(patch).every(Number.isFinite)&&await updateControls(patch))setDirty(false)}} className="w-full rounded bg-amber-300 px-4 py-2 text-sm font-bold text-slate-950 disabled:opacity-40 sm:w-auto">💾 Salvar delays</button>{dirty?<span className="text-xs text-amber-300">alterações pendentes — clique em Salvar delays</span>:<span className="text-xs text-slate-500">delays salvos: foco {controls.whisperFocusDelayMs}ms · digitar {controls.whisperKeystrokeDelayMs}ms · enviar {controls.whisperChatSendDelayMs}ms · fechar {controls.whisperChatCloseDelayMs}ms · pós-envio {controls.whisperAfterSendDelayMs}ms</span>}</div>
  <p className="mt-4 text-xs text-slate-500">💡 O leitor pode ficar ligado com o GSE desligado. O GSE só roda quando <b>Master GSE</b> está ON e o personagem também está marcado como rodando.</p></section>
  <div className="mt-5 flex flex-col gap-3 sm:flex-row"><button disabled={!chars.length||busy!==""} onClick={()=>void bulk("startAll")} className="rounded bg-emerald-500 px-5 py-2.5 font-bold text-slate-950 disabled:opacity-40">▶ Iniciar TODOS</button><button disabled={!chars.length||busy!==""} onClick={()=>void bulk("stopAll")} className="rounded bg-rose-500 px-5 py-2.5 font-bold disabled:opacity-40">■ Parar TODOS</button></div>
  <div className="mt-4 overflow-x-auto rounded-xl border border-slate-800"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-900 text-xs uppercase text-slate-500"><tr><th className="p-4">Personagem</th><th>Slot</th><th>Status</th><th>Tecla GSE</th><th>Intervalo</th><th></th></tr></thead><tbody className="divide-y divide-slate-800">{chars.map(ch=>{const s=states[ch]??{character:ch,running:false,keybind:"1",intervalMs:2000,updatedAt:""};return <tr key={ch}><td className="p-4 font-mono text-emerald-300">{ch}</td><td className="text-amber-300">wow{windows.find(w=>w.character===ch)?.slot||"?"}</td><td className={s.running?"text-emerald-300":"text-slate-500"}>● {s.running?"rodando":"parado"}</td><td><input className="w-24 rounded bg-slate-800 px-2 py-1.5" value={s.keybind} onChange={e=>setStates({...states,[ch]:{...s,keybind:e.target.value}})} onBlur={()=>void updateOne(ch,{keybind:states[ch].keybind})}/></td><td><input type="number" min="50" max="2000" className="w-28 rounded bg-slate-800 px-2 py-1.5" value={s.intervalMs} onChange={e=>setStates({...states,[ch]:{...s,intervalMs:Number(e.target.value)}})} onBlur={()=>void updateOne(ch,{intervalMs:states[ch].intervalMs})}/></td><td><button disabled={busy!==""||(!controls.gseMasterEnabled&&!s.running)} onClick={()=>void updateOne(ch,{running:!s.running})} className={`rounded px-4 py-2 font-bold disabled:opacity-40 ${s.running?"bg-rose-500":"bg-fuchsia-500"}`}>{s.running?"Parar":"Iniciar"}</button></td></tr>})}{!chars.length&&<tr><td colSpan={6} className="p-10 text-center text-slate-500">Nenhum personagem detectado.</td></tr>}</tbody></table></div>
 </div></main>
}
